__title__ = 'splitwise'
__description__ = 'Splitwise Python SDK'
__version__ = '2.2.0'
__url__ = 'https://github.com/namaggarwal/splitwise'
__download_url__ = 'https://github.com/namaggarwal/splitwise/tarball/v'+__version__
__build__ = 0x022400
__author__ = 'Naman Aggarwal'
__author_email__ = 'aggarwal.nam@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Naman Aggarwal'
